# Site settings
title: Code for Newark
email: ''
description: We are a local brigade of Code for America committed to making government work better in Newark.
baseurl: "https://code4newark.github.io/codefornewark.org/"
twitter_username: ''
github_username:  code4newark
paginate: 5
paginate_path: "blog/page:num/"

# Build settings
markdown: kramdown
